name = "TiSR"
uuid = "e1088136-a916-4db6-8e31-3a049800401f"
authors = ["Viktor Martinek", "Ophelia Frotscher", "Markus Richter", "Roland Herzog"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
